#!/usr/bin/env bash
set -euo pipefail
shopt -s nullglob
cd "$(dirname "${BASH_SOURCE[0]}")"

export TZ=UTC

declare parents
declare tree
declare tree4
declare repo
repo="$(git rev-parse --show-toplevel)"
cd "$repo"

if git rev-parse HEAD &>/dev/null; then
    parents="$(git rev-parse HEAD)"
else
    parents=
fi

git add .

tree="$(git write-tree)"
tree4="${tree:0:4}"

declare -i generation=0
    for parent in $parents; do
        for root in $(git rev-list --max-parents=0 "$parent"); do
            declare -i parent_generation_from_root
            parent_generation_from_root="$(git rev-list --count --ancestry-path "$root".."$parent")"
            if ((parent_generation_from_root >= generation)); then
                generation=$((parent_generation_from_root + 1))
            fi
        done
    done

declare message
message="r${generation}/${tree4}"

declare -i tick=32
declare -i step=64
declare -i drift=128
((0 == (step % tick)))
((step >= tick))
((drift >= step))

declare -i parent_timestamp=0
for parent in $parents; do
    declare -i this_parent_timestamp
    this_parent_timestamp="$(git log --format=%ct -1 "$parent")"
    if ((this_parent_timestamp > parent_timestamp)); then ((
        parent_timestamp = this_parent_timestamp
    )); fi
done

declare current_timestamp
current_timestamp="$(date +%s)"

declare -i timestamp
if ((current_timestamp - parent_timestamp > drift)); then
    timestamp=$((current_timestamp - (current_timestamp % step)))
else
    timestamp=$((parent_timestamp + tick - (parent_timestamp % tick)))
fi
declare date
date="$(date -d "@$timestamp")"

export GIT_COMMITTER_DATE="$date"
export GIT_AUTHOR_DATE="$date"
export GIT_COMMIT_MESSAGE="$message"

git commit . -m "$message"
git --no-pager log --format=raw --graph --decorate -n 2
